<?php

declare(strict_types=1);

namespace Cv;

/**
 * Downloads remote logo images once and caches them on disk, so the PDF
 * is not regenerated by re-downloading every logo on every request.
 *
 * If a logo can't be downloaded (network hiccup, 404, ...), resolve()
 * returns null and the caller simply skips drawing that logo - the CV
 * still generates correctly, just without that one image.
 */
final class LogoCache
{
    private string $cacheDir;

    public function __construct(string $cacheDir)
    {
        $this->cacheDir = rtrim($cacheDir, '/');

        if (!is_dir($this->cacheDir)) {
            @mkdir($this->cacheDir, 0775, true);
        }
    }

    /**
     * Returns a local filesystem path to the (possibly newly downloaded)
     * image, or null if it could not be made available.
     */
    public function resolve(?string $url): ?string
    {
        if ($url === null || $url === '') {
            return null;
        }

        // Allow local paths / already-local files to be used as-is too.
        if (!preg_match('#^https?://#i', $url)) {
            return is_file($url) ? $url : null;
        }

        $filename = sha1($url) . $this->guessExtension($url);
        $localPath = $this->cacheDir . '/' . $filename;

        if (is_file($localPath) && filesize($localPath) > 0) {
            return $localPath;
        }

        $contents = $this->download($url);

        if ($contents === null) {
            return null;
        }

        $tmpPath = $localPath . '.tmp-' . getmypid();

        if (@file_put_contents($tmpPath, $contents) === false) {
            return null;
        }

        // Atomic-ish rename so a concurrent request never sees a half-written file.
        @rename($tmpPath, $localPath);

        return is_file($localPath) ? $localPath : null;
    }

    private function download(string $url): ?string
    {
        if (function_exists('curl_init')) {
            $ch = curl_init($url);
            curl_setopt_array($ch, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_FOLLOWLOCATION => true,
                CURLOPT_MAXREDIRS      => 3,
                CURLOPT_CONNECTTIMEOUT => 5,
                CURLOPT_TIMEOUT        => 10,
                CURLOPT_SSL_VERIFYPEER => true,
                CURLOPT_USERAGENT      => 'cv-generator/1.0',
            ]);
            $body = curl_exec($ch);
            $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $error = curl_error($ch);
            curl_close($ch);

            if ($body === false || $error !== '' || $status < 200 || $status >= 300) {
                return null;
            }

            return $body;
        }

        // Fallback when the curl extension isn't available.
        $context = stream_context_create([
            'http' => ['timeout' => 10, 'follow_location' => 1, 'ignore_errors' => true],
            'https' => ['timeout' => 10],
        ]);

        $body = @file_get_contents($url, false, $context);

        return $body === false ? null : $body;
    }

    private function guessExtension(string $url): string
    {
        $path = (string) parse_url($url, PHP_URL_PATH);
        $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));

        return in_array($ext, ['png', 'jpg', 'jpeg', 'gif'], true) ? '.' . $ext : '.png';
    }
}
